# Generated by Django 6.0.7 on 2026-07-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('architect_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('designer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='')),
                ('owner', models.CharField(default='', max_length=140)),
                ('project_value', models.IntegerField(default=0)),
                ('start_date', models.DateField(default='')),
                ('completion_date', models.DateField(default='')),
                ('additional_content', models.TextField(default='')),
                ('architect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.architect')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.designer')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('slug', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='projects_tmp')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
