# Generated by Django 6.0.7 on 2026-07-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('owner', models.CharField(max_length=140)),
                ('architect_engineer', models.CharField(max_length=140)),
                ('project_value', models.IntegerField()),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('additional_content', models.TextField()),
            ],
        ),
    ]
