# Generated by Django 6.0.7 on 2026-08-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectDesigner',
            fields=[
                ('a_d_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='projects_tmp')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('slug', models.CharField(blank=True, default='', max_length=100)),
                ('desc_head', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(default='')),
                ('project_value', models.CharField(default='', max_length=12)),
                ('start_date', models.DateField(blank=True, default='', null=True)),
                ('completion_date', models.DateField(blank=True, default='', null=True)),
                ('featured', models.BooleanField(default=True)),
                ('architect_designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.architectdesigner')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.owner')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.photo')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='photo_1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_1', to='projects.projectphoto'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_2', to='projects.projectphoto'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_3', to='projects.projectphoto'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_4', to='projects.projectphoto'),
        ),
    ]
