# Generated by Django 6.0.7 on 2026-07-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designer',
            new_name='ArchitectDesigner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='architect',
        ),
        migrations.RenameField(
            model_name='architectdesigner',
            old_name='designer_id',
            new_name='a_d_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='designer',
            new_name='architect_designer',
        ),
        migrations.DeleteModel(
            name='Architect',
        ),
    ]
