# Generated by Django 6.0.7 on 2026-08-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_1', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_2', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_3', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_4', to='projects.photo'),
        ),
    ]
