# Generated by Django 6.0.7 on 2026-08-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_featured_alter_project_photo_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPhoto',
        ),
    ]
