# Generated by Django 6.0.7 on 2026-08-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_projectphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectdesigner',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='second_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_owner', to='projects.owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='architect_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.architectdesigner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
