# Generated by Django 6.0.7 on 2026-08-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_architectdesigner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='photo',
            name='file_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=20),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(height_field='file_height', upload_to='projects_tmp', width_field='file_width'),
        ),
        migrations.AlterField(
            model_name='project',
            name='architect_designer',
            field=models.ForeignKey(blank=True, help_text='Architect or Design firm (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.architectdesigner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='for future filters on the projects index (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='The full description of this project (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc_head',
            field=models.CharField(blank=True, help_text='The header above the project description. Especially useful with parent and child projects (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='in the list of projects to be featured on the homepage (the first five featured will show)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The owner of the finished project (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='If this is the second phase of a previous project, please select the previous project above (optional: use this or a slug)', limit_choices_to={'parent_project': None}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_1', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_2',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_2', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_3',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_3', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_4',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_4', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.CharField(blank=True, default='', help_text='Please use commas and no dollar sign', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_owner',
            field=models.ForeignKey(blank=True, help_text='A second owner (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_owner', to='projects.owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, default='', help_text='Creates the url of your project, guyhopkins.com/projects/your-project-slug (optional: leave blank when a Parent Project is selected) ', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', help_text='The title of this project (required)', max_length=100),
        ),
    ]
