# Generated by Django 6.0.7 on 2026-07-30 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_slug_alter_projectphoto_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo_1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_1', to='projects.projectphoto'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_2', to='projects.projectphoto'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_3', to='projects.projectphoto'),
        ),
        migrations.AddField(
            model_name='project',
            name='photo_4',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Photo_4', to='projects.projectphoto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_value',
            field=models.CharField(default='', max_length=12),
        ),
    ]
