# Generated by Django 6.0.7 on 2026-08-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_category_options_photo_file_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='listed',
            field=models.BooleanField(default=True, help_text='Whether or not this page is listed on the Projects index page (it will still accessible by url)'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(height_field='file_height', upload_to='', width_field='file_width'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, help_text='For future filters on the projects index (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='In the list of projects to be featured on the homepage (the first five featured will show)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_1',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Photo_1', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_2',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Photo_2', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_3',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Photo_3', to='projects.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo_4',
            field=models.ForeignKey(blank=True, default='', help_text='Choose an existing photo or add and upload a new one with the plus button (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Photo_4', to='projects.photo'),
        ),
    ]
