# Generated by Django 6.0.7 on 2026-08-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_architectdesigner_slug_category_slug_owner_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='architect_designer',
            field=models.ForeignKey(blank=True, help_text='Architect or Engineer firm (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.architectdesigner'),
        ),
    ]
