# Generated by Django 6.0.7 on 2026-08-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_photo_processed_alter_project_architect_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='processed',
        ),
    ]
