# Generated by Django 6.0.7 on 2026-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_photo_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='processed',
            field=models.BooleanField(default=True),
        ),
    ]
